### ISSUE TITLE
Weather daily does not display/refresh automatically

### ISSUE THREAD

**Issue by Soulreaver1977** [stevehsudrawing/quantoflx#1] opened 2024-11-09 16:11 UTC
Although the current weather skin is active, the daily weather overview is not updated automatically. At startup, I have to refresh the current weather skin every time so that the exclamation mark disappears and the daily weather forecast is displayed.

**Comment by stevehsudrawing** [comment] 2024-11-10 05:09
First of all, thank you for your feedback. 

It should be noted that the other components of "Weather" need to read the weather information within a short period (currently 500ms) of time after the information in the "Weather - Current" skin is successfully loaded. Therefore, you should decide on your layout before you can enable the weather feature by refreshing the "Weather - Current" skin.

This issue may be caused by the too short period of time available for read. It will be fixed in the next snapshot version.

**Closed** 2024-11-10 11:36 UTC
Labels: bug
